 # Site settings 
title: "Cecilia's coding journey"
description: 'your web description'
keywords: 'blog, software engineer'
url: 'https://cecilia-xu.github.io' # your host

# nav 
nav: 
  Home: '/'
  Categories: '/tags.html'
  Timelines: '/timeline.html'
  About me: '/about.html'
  Links: '/friendLink.html'

# Author
author: true
name: 'Cecilia Xu'
NickName: ''
webtitle: "Cecilia's coding journey"
bio: 'Software engineer, SEUer, PITT, She/Her/Hers'
about: true
aboutyou: "I am currently a software engineer in Los Angeles. I got my master's degree in Information Science at University of Pittsburgh and got my bechelor's degree at Southeast University.<br> Fun facts about me: <br>1. My undergraduate major is Finance. <br>2. My favorite singer is Avril Lavigne! <br> 3. I landed my job during COVID-19 pandemic." 
portraits: '/assets/profile.jpeg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:xu_xiaoqian@outlook.com'
  weixin: '' # 你的微信二维码存放的地址
  github: 'https://github.com/Cecilia-xu'

# 分页
paginate: 2
paginatepath: ['page:num']

# since
footer:
  since: 2020

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# Code highlighter by rouge
highlighter: rouge
# Code themes by pygments: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 
pygmentsTheme: 'default'

# Friend Link
friends:
  jekyll: 'https://www.jekyll.com.cn/'

# Comments, choose from disqus,livere, and Gitment
# disqus
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# livere
livere: false
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment OAuth Application
Gitment: true
Gitment_owner: 'Cecilia-xu'  # github username
Gitment_repo: 'Cecilia-xu.github.io'  #git repo name
client_id: '324703712c8c106fed45'  # 注册 OAuth Application 后获得的 client_id
client_secret: 'c2a80c620705ea167e50aa2f516f15c181cb2544'  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['twitter','facebook','qq', 'wechat', 'weibo']

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)

